services:
  nginx:
    image: nginx:1.24
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - var-www-html:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/

  php:
    # image: php:8.2-fpm
    build: 
      context: .
      dockerfile: ./php/dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - var-www-html:/var/www/html
      # - ./magento:/magento
    depends_on:
      nginx:
        condition: service_started
      mysql:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./database:/dump
    working_dir: /dump
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env
  
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://$SERVER_IP:9200/"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

volumes:
  var-www-html:
    # external: true
