services:
  nginx:
    image: nginx:1.24
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - var-www-html:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/

  php:
    # image: php:8.2-fpm
    build: 
      context: .
      dockerfile: /php/dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - var-www-html:/var/www/html
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      USERNAME_MAGENTO_KEY: ${USERNAME_MAGENTO_KEY}
      PASSWORD_MAGENTO_KEY: ${PASSWORD_MAGENTO_KEY}
    working_dir: /var/www/html
    command: >
      sh -c "composer install && 
      ./install-magento.sh $MYSQL_USER $MYSQL_PASSWORD $MYSQL_DATABASE $USERNAME_MAGENTO_KEY $PASSWORD_MAGENTO_KEY"
    depends_on:
      nginx:
        condition: service_started
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    # volumes:
    #   - ./elastic:/usr/share/elasticsearch/data
    env_file:
      - .env
volumes:
  var-www-html: